portHome/urls.py
from django.conf.urls import url

from portHome import views

app_name = 'portHome'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^about/$', views.about_me, name='about'),
    url(r'^details/(?P<project_id>[0-9]+)/$', views.project_details, name='details'),
    url(r'^recipesearch/', views.treact, name='treact')
]

portfolio/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('portHome.urls')),
    url(r'^admin/', admin.site.urls),
]

portHome/models.py
from django.db import models

TYPE_CHOICES = (('Frontend','Frontend'), ('Backend','Backend'), ('Legacy','Legacy'), ('Coding','Coding'),)

class Project(models.Model):
    name = models.CharField(max_length=100)
    type = models.CharField(max_length=100, choices=TYPE_CHOICES)
    technologies = models.ManyToManyField('Technology')
    description = models.TextField()
    link = models.CharField(max_length=200)
    git_link = models.CharField(max_length=200)
    image = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class AdditionalImage(models.Model):
    name = models.CharField(max_length=100)
    project = models.ForeignKey('Project')
    link = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Technology(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

portHome/views.py
from django.shortcuts import render
from .models import Project, AdditionalImage

# Create your views here.
def home(request):
    projects = Project.objects.all()
    return render(request, 'portHome/home.html', {'projects': projects, 'page': 'home'})

def about_me(request):
    return render(request, 'portHome/about_me.html', {'page': 'about_me'})

def project_details(request, project_id):
    project = Project.objects.get(id=project_id)
    try:
        additionalImages = AdditionalImage.objects.get(project = project)
    except AdditionalImage.DoesNotExist:
        additionalImages = []
    return render(request, 'portHome/details.html', {'project': project, 'images': additionalImages, 'page': 'details'})

def treact(request):
    return render(request, 'portHome/treact.html')

portHome/templates/portHome/about_me.html
{% extends 'portHome/base.html' %}
{% block content %}
{% load static %}

<div class='centredBlock flexBox' id='aboutMe'>
    <img src='https://avatars2.githubusercontent.com/u/19530989?v=3&s=460'/>
    <div id='details'>
      <h1>About Me</h1>
      <p>
      My name is Simon Leigh. Originally from Newcastle, England, I have always taken
      and unconventional route through life in order to keep challenging myself. <br>
      After years of high level sports I needed a fresh challenge and choose to study
      Japanese in university. Two years in I took a gap-year during which time I moved
      to Japan and worked teaching English first in Shizuoka before moving to Kawasaki,
      Kanagawa for most of the year. <br>
      I then came to Akita International University where I transferred into their Global
      Studies program, mainly studying Political Science with a peripheral focus on media. <br>
      I have been programming as a hobby for a couple of years in the little free time I have.
      Managing to become relatively proficient in Python and Javascript along with a pretty
      successful foray into C#. <br>
      I still have much to learn and am always looking to take my skills to the next level. <br>
      </p>
      <h4>TODO:</h4>
      <ul>
        <li>Style portfolio so it doesn't look like garbage</li>
        <li>Add more detailed description for projects</li>
        <li>Write Docs for recipe API project</li>
        <li>So many more...</li>
      </ul>
      <div>
        <a href='https://github.com/ButteryCrumpet' target='_blank'><h4>My GitHub<h4></a>
        <a href="{% static 'portHome/SimonLeighResume.pdf' %}" target='_blank'><h4>My Resume</h4></a>
      </div>
    </div>
</div>
{% endblock %}

portHome/templates/portHome/base.html
{% load static %}
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"/>
  <link rel="stylesheet" href="{% static 'portHome/style.css' %}" />
  <link href="https://fonts.googleapis.com/css?family=Lato:400,700|Lora:400,400i" rel="stylesheet">
  <script src="{% static "portHome/jquery-3.2.1.min.js" %}"></script>
  <title>PanDev</title>
</head>
<header class='nav navbar-inverse' role='navigation'>
    <div class='navbar-header'>
      <a href=
      {% if page == 'home' %}
        "#fullscreen-home"
      {% else %}
        "{% url 'portHome:home' %}"
      {% endif %}
      class='nav navbar-brand'>Pandevelop</a>
    </div>
    <ul class='nav navbar-nav navbar-right'>
      <li><a href="{% url 'portHome:about' %}">About Me</a></li>
      <li><a href=
        {% if page == 'home' %}
        "#frontend"
        {% else %}
        "{% url 'portHome:home' %}#frontend"
        {% endif %}
        >Projects</a></li>
      <li><a href=
        {% if page == 'home' %}
        "#footer_target"
        {% else %}
        "{% url 'portHome:home' %}#footer_target"
        {% endif %}
        >Contact</a></li>
    </ul>
</header>

 {% block content %}
 {% endblock %}

 <div class='footer' id='footer_target'>
   <div class='container'>
     <h3>Contact</h3>
     <p>Uni email: b1310321@gl.aiu.ac.jp</p>
     <p>Personal email: bumpetycrumpety@gmail.com</p>
     <p>Tel: 080-5562-7260</p>
   </div>
 </div>

 <script src="{% static "portHome/smoothscroll.js" %}"></script>

portHome/templates/portHome/details.html
{% extends 'portHome/base.html' %}
{% block content %}

<section class='content' id='fullscreen-home'>
    <div class='col-xs-10 centredBlock'>
        <div class='row' id='detail-row'>
            <div class='col-xs-8'>
                <div class='detailTitle'>
                    <h1>{{project.name}}</h1>
                </div>
                <h4>Languages</h4>
                <p>
                    <i>
                        {% for language in project.languages.all %}
                        {{language.name}},
                        {% endfor %}
                    </i>
                </p>
            </div>
            <div class='col-md-4 col-xs-6 detailImage'>
                <img src='{{project.image}}'/>
            </div>
        </div>
        <div class='col-xs-8 col-xs-offset-1'>
            <h3>Description</h3>
            <div class='detailDescription'>
                <p>{{project.description}}</p>
            </div>
        </div>
    </div>
</section>

{% endblock %}

portHome/templates/portHome/home.html
{% extends 'portHome/base.html' %}
{% block content %}

<section id='fullscreen-home' class='content'>
  <div id='welcome-message'  class='col-md-10 col-md-offset-2'>
    <h1>PanDev</h1>
    <p class='lead'>Pan-development.</p>
    <p class='lead'>
      A small collection of projects jammed together into some form of portfolio.
      <br>Slowly but steadily being added to and improved
    </p>
    <a href="{% url 'portHome:about' %}" type='button' class='btn btn-success'>More about me</a>
    <a href="#frontend" type='button' class='btn btn-primary'>Projects</a>
  </div>
</section>

<div id='frontend' class='parallax'>
  <div>
    <h1>Projects</h1>
  </div>
</div>

<section class='content'>

  <div class='container-fluid'>
    <div class='section-description'>
      <p>
        A selection of projects, mostly messy and incomplete <br>
        I do my best to add as I can when I have time.
      </p> <!-- centre it -->
    </div>
    <ul class='projects clearfix'>
      {% for project in projects %}
      <li class='project'>
        <div class='row'>
          <h2>{{project.name}}</h2>
          <div class='col-xs-8'>
            <p>
              <i>
                {% for technology in project.technologies.all %}
                {{technology.name}}{% if not forloop.last %},{% endif %}
                {% endfor %}
              </i>
            </p>
            <p>{{project.description}}</p>
            <a href='{{project.git_link}}'>GitHub</a>
          </div>
          <div class='col-xs-3 col-xs-offset-1 detailImage'>
            <a href='{{ project.link }}'>
              <img class='projectImage' src="{{project.image}}"/>
            </a>
          </div>
        </div>
      </li>
      {% endfor %}
    </ul>
    </div>
  </div>

</section>

{% endblock %}

portHome/templates/portHome/treact.html
{% load static %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'portHome/treact-style.css' %}">
    <title>Terraria Recipe Search</title>
  </head>
  <body>
    <h2>Search Terraria Item (placeholder title)</h2>
    <div id="root"></div>
  </body>
  <script src="{% static 'portHome/treact.js' %}"></script>
</html>